// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEMn6_ffzRF9Xm96DcuOOcfc1iU2YU-Cg',
    appId: '1:435031611747:web:e735de88599ef551341b56',
    messagingSenderId: '435031611747',
    projectId: 'untitled-2544e',
    authDomain: 'untitled-2544e.firebaseapp.com',
    storageBucket: 'untitled-2544e.appspot.com',
    measurementId: 'G-00D46JTRN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI03btfPPjHo_Oml75bJQMyoKihD1_XK8',
    appId: '1:435031611747:android:0c493a93052e3a02341b56',
    messagingSenderId: '435031611747',
    projectId: 'untitled-2544e',
    storageBucket: 'untitled-2544e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfgfA7eKLbielMmbztr4MvsO-HQ3anG3M',
    appId: '1:435031611747:ios:da968b271915e14b341b56',
    messagingSenderId: '435031611747',
    projectId: 'untitled-2544e',
    storageBucket: 'untitled-2544e.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfgfA7eKLbielMmbztr4MvsO-HQ3anG3M',
    appId: '1:435031611747:ios:34de50a4fe281e06341b56',
    messagingSenderId: '435031611747',
    projectId: 'untitled-2544e',
    storageBucket: 'untitled-2544e.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
